Repository particuleio/terraform-kubernetes-addons, pull requests merged in 2021-03, with the labels that each got.

#24 feat(cert-manager): scaleway webhook is enabled only if cert-manager is enabled
  modules/scaleway/cert-manager.tf
Labels: bug

#25 feat: add fluxv2 addons
  README.md
  flux2.tf
  modules/aws/README.md
  modules/aws/flux2.tf
  modules/aws/versions.tf
  modules/scaleway/README.md
  modules/scaleway/examples/terraform/main.tf
  modules/scaleway/flux2.tf
  modules/scaleway/versions.tf
  variables.tf
  versions.tf
Labels: enhancement

#27 feat: Add kyverno support
  README.md
  kyverno.tf
  modules/aws/README.md
  modules/aws/kyverno.tf
  modules/scaleway/README.md
  modules/scaleway/kyverno.tf
  variables.tf
Labels: enhancement

#23 feat: Add AWS EFS CSI Driver
  README.md
  modules/aws/README.md
  modules/aws/aws-efs-csi-driver.tf
  modules/aws/variables-aws.tf
Labels: enhancement

#31 fix: flux2 should work with all use cases
  README.md
  flux2.tf
  modules/aws/README.md
  modules/scaleway/README.md
Labels: bug

#32 chore: add new issues templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation

#18 feat: add prometheus exporters
  README.md
  modules/aws/README.md
  modules/aws/prometheus-adapter.tf
  modules/aws/prometheus-blackbox-exporter.tf
  modules/aws/prometheus-cloudwatch-exporter.tf
  modules/aws/variables-aws.tf
  modules/scaleway/README.md
  modules/scaleway/prometheus-adapter.tf
  modules/scaleway/prometheus-blackbox-exporter.tf
  prometheus-adapter.tf
  prometheus-blackbox-exporter.tf
  variables.tf
Labels: enhancement

#33 feat: implement renovate logic
  .github/renovate.json
  .github/workflows/terraform.yml
  cert-manager.tf
  flux.tf
  helm-dependencies.yaml
  ingress-nginx.tf
  istio-operator.tf
  karma.tf
  keycloak.tf
  kong.tf
  kube-prometheus.tf
  kyverno.tf
  locals.tf
  loki-stack.tf
  metrics-server.tf
  modules/aws/aws-ebs-csi-driver.tf
  modules/aws/aws-efs-csi-driver.tf
  modules/aws/aws-for-fluent-bit.tf
  modules/aws/aws-load-balancer-controller.tf
  modules/aws/aws-node-termination-handler.tf
  modules/aws/calico.tf
  modules/aws/cert-manager.tf
  modules/aws/cluster-autoscaler.tf
  modules/aws/external-dns.tf
  modules/aws/helm-dependencies.yaml
  modules/aws/ingress-nginx.tf
  modules/aws/kong.tf
  modules/aws/kube-prometheus.tf
  modules/aws/loki-stack.tf
  modules/aws/prometheus-cloudwatch-exporter.tf
  modules/aws/thanos-memcached.tf
  modules/aws/thanos-storegateway.tf
  modules/aws/thanos-tls-querier.tf
  modules/aws/thanos.tf
  modules/scaleway/cert-manager.tf
  modules/scaleway/external-dns.tf
  modules/scaleway/helm-dependencies.yaml
  modules/scaleway/ingress-nginx.tf
  node-problem-detector.tf
  prometheus-adapter.tf
  prometheus-blackbox-exporter.tf
  sealed-secrets.tf
  strimzi-kafka-operator.tf
Labels: enhancement

#60 feat: add vault
  README.md
  helm-dependencies.yaml
  modules/aws/README.md
  modules/aws/vault.tf
  modules/scaleway/README.md
  modules/scaleway/vault.tf
  variables.tf
  vault.tf
Labels: enhancement

#67 fix: Use proper URL for thanos-replicate dashboard
  modules/aws/kube-prometheus.tf
Labels: bug

#68 fix: Create thanos policy if bucket is created
  modules/aws/thanos.tf
Labels: bug

#69 fix: revert recent breaking thanos change
  modules/aws/thanos.tf
Labels: bug
